[package]
name = "recastssl"
authors = ["404"]
version = "2.0.1"
edition = "2024"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"

[profile.release.package."*"]
opt-level = 3

[dependencies]
jni = "0.21.1"
openssl = "0.10.75"

[lib]
crate-type = ["cdylib"]
